# Dockerfile.init-runner

FROM debian:bookworm-slim

WORKDIR /app

# Instala ferramentas mínimas
RUN apt-get update && apt-get install -y bash coreutils

# Copia os arquivos necessários
COPY scripts/ scripts/
COPY templates/ templates/
COPY .env .env

# Garante que os scripts são executáveis
RUN chmod +x scripts/*.sh

# Executa o script principal
ENTRYPOINT ["bash", "scripts/run-all.sh"]
