# ============================================================================
# DOCKER COMPOSE HÍBRIDO - ANPD PostgreSQL Infrastructure
# ============================================================================
# Este arquivo funciona tanto para desenvolvimento local quanto GitOps/Portainer
#
# 🏠 MODO LOCAL:
#   - Use arquivo .env com APPS_CONFIG (formato completo)
#   - Execute: docker-compose up -d
#
# 🚀 MODO GITOPS:
#   - Configure environment variables no Portainer Stack
#   - Aplicações definidas em config/apps.conf
#   - Execute: Use este mesmo arquivo no Portainer
# ============================================================================

services:
  postgres:
    image: postgres:15
    container_name: ${POSTGRES_CONTAINER_NAME:-anpd-postgres-dev}
    restart: always
    environment:
      # Configurações principais
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_TIMEZONE: ${POSTGRES_TIMEZONE:-America/Sao_Paulo}

      # Configurações adicionais para estabilidade
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS:---auth-host=scram-sha-256 --auth-local=trust}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD:-scram-sha-256}

      # Senhas das aplicações (para GitOps - ignoradas no modo local)
      BACKLOG_PASSWORD: ${BACKLOG_PASSWORD:-}
      CONTROLADORES_PASSWORD: ${CONTROLADORES_PASSWORD:-}
      # Adicione aqui senhas de novas apps conforme necessário

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - postgres_network
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -p 5432 || exit 1']
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ${PGADMIN_CONTAINER_NAME:-anpd-pgadmin-dev}
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./config/servers.json:/pgadmin4/servers.json:ro
      - ./pgadmin-init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    ports:
      - '${PGADMIN_PORT:-8085}:80'
    networks:
      - postgres_network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--quiet',
          '--tries=1',
          '--spider',
          'http://localhost/misc/ping'
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  init-runner:
    build:
      context: .
      dockerfile: Dockerfile.init-runner
    container_name: ${INIT_CONTAINER_NAME:-anpd-init-runner}
    environment:
      # Forçar modo GitOps (defina GITOPS_MODE=true no Portainer)
      GITOPS_MODE: ${GITOPS_MODE:-false}

      # Auto-sync de bancos (defina AUTO_SYNC_DATABASES=true no Portainer)
      AUTO_SYNC_DATABASES: ${AUTO_SYNC_DATABASES:-false}

      # Para modo LOCAL (APPS_CONFIG com credenciais completas)
      APPS_CONFIG: ${APPS_CONFIG:-}

      # Para modo GITOPS (senhas individuais + config/apps.conf)
      BACKLOG_PASSWORD: ${BACKLOG_PASSWORD:-}
      CONTROLADORES_PASSWORD: ${CONTROLADORES_PASSWORD:-}

      # Configurações do PostgreSQL (para auto-sync)
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-}

      # Variáveis legadas (para compatibilidade - serão removidas)
      BACKLOG_DB: ${BACKLOG_DB:-}
      BACKLOG_USER: ${BACKLOG_USER:-}
      BACKLOG_PASS: ${BACKLOG_PASS:-}
    volumes:
      - ./init:/app/init
      - ./config:/app/config
    depends_on:
      postgres:
        condition: service_healthy
    restart: 'no'
    networks:
      - postgres_network

volumes:
  postgres_data:
    name: ${POSTGRES_VOLUME_NAME:-anpd_postgres_data}
  pgadmin_data:
    name: ${PGADMIN_VOLUME_NAME:-anpd_pgadmin_data}

networks:
  postgres_network:
    name: ${NETWORK_NAME:-anpd_postgres_network}
    driver: bridge
