services:
  postgres:
    image: postgres:15
    container_name: anpd-postgres-dev
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata-anpd-dev:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - pg-net
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: anpd-pgadmin-dev
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./config/servers.json:/pgadmin4/servers.json
    ports:
      - '8085:80'
    networks:
      - pg-net
    depends_on:
      - postgres

  init-runner:
    image: debian:bookworm-slim
    container_name: run-init-scripts
    working_dir: /app
    entrypoint: ['/bin/bash', '-c']
    command: 'ls -la /app/scripts && echo "---" && cat /app/scripts/run-all.sh || echo "⚠️  Arquivo não encontrado"'
    volumes:
      - ./scripts:/app/scripts
      - ./templates:/app/templates
      - ./init:/app/init
      - ./config:/app/config
      - ./.env:/app/.env
    depends_on:
      - postgres
    restart: 'no'

volumes:
  pgdata-anpd-dev:
  pgadmin-data:

networks:
  pg-net:
