services:
  postgres:
    image: postgres:15
    container_name: anpd-postgres-dev
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata-anpd-dev:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - pg-net
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: anpd-pgadmin-dev
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./config/servers.json:/pgadmin4/servers.json
    ports:
      - '8085:80'
    networks:
      - pg-net
    depends_on:
      - postgres

  init-runner:
    build:
      context: .
      dockerfile: Dockerfile.init-runner
    container_name: run-init-scripts
    volumes:
      - ./init:/app/init
      - ./config:/app/config
    environment:
      - BACKLOG_DB
      - BACKLOG_USER
      - BACKLOG_PASS
      - POSTGRES_DB
      - POSTGRES_USER
    depends_on:
      - postgres
    restart: 'no'

volumes:
  pgdata-anpd-dev:
  pgadmin-data:

networks:
  pg-net:
