services:
  postgres:
    image: postgres:15
    container_name: postgres-dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-docker_infra_pg_dev}
      POSTGRES_USER: ${POSTGRES_USER:-dev_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev_network

volumes:
  postgres_data:

networks:
  dev_network:
    driver: bridge
